export const CHECKOUT = "CHECKOUT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const SHOW_CLEAR_CART_MODAL = "SHOW_CLEAR_CART_MODAL";